# Generated by Django 2.2 on 2020-03-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200314_0647'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(choices=[('common', 'Общий'), ('hidden', 'Скрытый'), ('private', 'Приватный')], default='common', max_length=50, verbose_name='Тип'),
        ),
    ]
