# Generated by Django 2.2 on 2020-03-14 11:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_auto_20200314_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='private_group',
            field=models.ManyToManyField(related_name='file_private', to=settings.AUTH_USER_MODEL, verbose_name='Группа'),
        ),
    ]
